# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-19 02:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=40)),
                ('keterangan', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='berita',
            name='kategori',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='blog.Kategori'),
        ),
    ]
